# Generated by Django 4.0.2 on 2022-02-07 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code')),
                ('label', models.CharField(max_length=50, verbose_name='label')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 's',
            },
        ),
        migrations.CreateModel(
            name='Investments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('date', models.DateTimeField(verbose_name='DateTime')),
                ('order_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], default='buy', max_length=50, verbose_name='Order type')),
                ('price', models.FloatField(verbose_name='Price')),
                ('quantity', models.FloatField(verbose_name='Quantity')),
                ('cost', models.FloatField(blank=True, verbose_name='Cost')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investments.currency', verbose_name='Currency')),
            ],
            options={
                'verbose_name': 'Invests ',
                'verbose_name_plural': 'Invests s',
            },
        ),
    ]
