# Generated by Django 4.0.2 on 2022-02-08 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name': 'Currency', 'verbose_name_plural': 'Currencies'},
        ),
        migrations.AlterModelOptions(
            name='investments',
            options={'verbose_name': 'Investment', 'verbose_name_plural': 'Investments'},
        ),
    ]
