# Generated by Django 4.0.2 on 2022-02-08 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0002_alter_currency_options_alter_investments_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('url', models.URLField(verbose_name='Url')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='currency',
            old_name='label',
            new_name='name',
        ),
        migrations.AddField(
            model_name='investments',
            name='exchange',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='investments.exchange', verbose_name='Exchange'),
        ),
    ]
