# Generated by Django 4.0.2 on 2022-02-11 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0004_alter_exchange_options_currency_user_exchange_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='user',
        ),
        migrations.RemoveField(
            model_name='exchange',
            name='user',
        ),
    ]
