# Generated by Django 4.0.2 on 2022-02-13 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0005_remove_currency_user_remove_exchange_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='investments',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='investments',
            name='reference',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='reference'),
        ),
    ]
