# Generated by Django 4.0.2 on 2022-02-13 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0006_investments_comment_investments_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('category', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=50, verbose_name='Order type category')),
            ],
            options={
                'verbose_name': 'Order type',
                'verbose_name_plural': 'Order types',
            },
        ),
        # migrations.AlterField(
        #     model_name='investments',
        #     name='order_type',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investments.ordertype', verbose_name='Order type'),
        # ),
    ]
